"""Initial migration

Revision ID: c5b4a9e2dbe6
Revises: 
Create Date: 2025-01-24 10:15:48.732242
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5b4a9e2dbe6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('special_occupation_reservation')

    # Alter the 'reservation_time' column in 'reservation' table
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('reservation_time',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.DateTime(),
               existing_nullable=False,
               postgresql_using="reservation_time::timestamp without time zone")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column(
            'reservation_time',
            existing_type=sa.DateTime(),
            type_=sa.VARCHAR(length=20),
            postgresql_using="reservation_time::text"
        )

    # Recreate the 'special_occupation_reservation' table
    op.create_table('special_occupation_reservation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('order_purpose', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('number_of_person', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reservation_time', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='special_occupation_reservation_pkey')
    )
    # ### end Alembic commands ###
